title: Commit Messages
description: Reflections on code, craft, and the future of software
author: Andrey Samsonov
url: "https://msg.samsonov.io"
baseurl: ""

permalink: /:year-:month-:day-:title/

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-og-image

og_image:
  output_dir: "assets/images/og"
  domain: "msg.samsonov.io"
  image: "/assets/images/avatar.png"
  force: true
  verbose: true

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
